### ISSUE TITLE
pkl file does not exist

### ISSUE THREAD

**Issue by jensen-Shen-Li** [srzer/LaMo-2023#2]
Hi, Thank you for your excellent work and congratulations for LaMo being accepted by ICLR 2024.
I downloaded the mujoco.tar from the pkl link you provided, unzipped it and found that there was no "hopper-medium-1-d1-v2.pkl", could you provide the whole pkl files, thank you.
![image](https://github.com/user-attachments/assets/097769a4-7b32-43b6-8e7a-c633fa81dca1)

**Comment by srzer** [comment]
Hi! The original data (a.k.a. ratio=1) are accessible online, so we did not provide the pkl with ratio=1. You can directly get it by 
```
cd data
python download_d4rl_datasets.py
```
